### ISSUE TITLE
Issue when pdf file shared from Shopify

### ISSUE THREAD

**Issue by mposch-Z** [Nikhil1999/uri-to-file#6]
The library seems to struggle resolving PDF documents shared from Shopify on Android only, which in this case is a shipping label I've generated.  The shared link comes in as "content://com.google.android.apps.docs.fetcher.FileProvider/sLQRfJRPlfqp5v9QkmEinqUr5sLHzMLhcAfldRnhP1Y%3D?_display_name=shipping_label_1003.pdf&mime_type=application%2Fpdf&_size=22438"

Uri.parse doesn't seem to play nicely either.  I'm thinking this is an issue on Shopify's end but am curious about others thoughts/workarounds.

**Comment by Nikhil1999** [comment]
Hi @mposch-Z 
I have fixed this issue in the uri_to_file 0.2.0 

But there are some breaking changes 

- Breaking changes
   - Signature changed for isUriSupported() & toFile() both now requires string uri
- Important note
   - Don't pass uri parameter using [Uri] object via uri.toString()
   - Because uri.toString() changes the string to lowercase which causes this package to misbehave
   - If you are using uni_links package for deep linking purpose
   - Pass the uri string using getInitialLink() or linkStream
   
Can you please check if your issue is resolved with this update?

**Comment by mposch-Z** [comment]
I've since worked around the issue.  I will have to restore some code to an old state to verify, can't perform this immediately atm.

**Comment by Nikhil1999** [comment]
No problem
Take your time

**Comment by Nikhil1999** [comment]
Closing this issue as fixed with the latest v1.0.0
